baseURL = "https://moveitraleigh.com/"
languageCode = "en-us"
title = "Move It Raleigh"

[blackfriday]
  hrefTargetBlank = true

[params]
  description = "Text about my cool site"
  images = ["site-feature-image.jpg"]
  title = "My cool site"
  header_image = "img/mir-full.png"

# [taxonomies]
#   series = "series"
#   event = "events"
#   tag = "tags"
#   category = "categories"
    
[menu]
  [[menu.main]]
    identifier = "about"
    name = "Who We Are"
    title = "who we are title"
    url = "/about/"
    weight = -110
    
  [[menu.main]]
    identifier = "concert"
    name = "Benefit Concert"
    title = "how to give title"
    url = "/events/1st-annual-benefit/"
    weight = -100

  [[menu.main]]
    identifier = "sponsor"
    name = "Donate"
    url = "/sponsor/"
    weight = -90

  [[menu.main]]
    identifier = "connect"
    name = "Connect"
    title = "Connect With Us"
    url = "/connect/"
    weight = -80
