baseURL = "https://moveitraleigh.com/"
enableRobotsTXT = true
languageCode = "en-us"
title = "Move It Raleigh"
disableKinds = ["taxonomyTerm"]

[blackfriday]
  hrefTargetBlank = true
  
[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":fileModTime", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]
  
[params]
  description = "Move It Raleigh is a community-based campaign to encourage residents in the Triangle area to get out and move, with a specific focus on the performing arts."
  images = ["/img/banner.jpg"]
  title = "Move It Raleigh"
  header_image = "img/mir-full.png"

 [taxonomies]
   participant = "participants"
   sponsor = "sponsors"
# [taxonomies]
#   series = "series"
#   event = "events"
#   tag = "tags"
#   category = "categories"
    
[menu]
  [[menu.main]]
    identifier = "about"
    name = "Who We Are"
    title = "Who We Are"
    url = "/about/"
    weight = -110
    
  [[menu.main]]
    identifier = "past-events"
    name = "Past Events"
    title = "Past Events"
    url = "/events/1st-annual-benefit/"
    weight = -100

  # [[menu.main]]
  #   identifier = "donate"
  #   name = "Donate"
  #   url = "/donate/"
  #   weight = -90

  [[menu.main]]
    identifier = "connect"
    name = "Join the MOVEment"
    title = "Connect With Us"
    url = "/connect/"
    weight = -80
