[build]
  functions = "lambda"
  command = "hugo && npm run build:lambda"
  
[context.phase3.environment]
  NODE_ENV='staging'
  
[[redirects]]
  from = "/checkout"
  to = "/.netlify/functions/checkout"
  status = 200
