[build]
  functions = "functions"
  command = "hugo && npm run build:lambda"

[context.production.environment]
  BRANCH_ENV = "prod"
  HUGO_GOOGLEANALYTICS = "UA-128594050-1"

[context.staging.environment]
  BRANCH_ENV = "staging"
  HUGO_GOOGLEANALYTICS = "UA-128594050-2"

[[redirects]]
  from = "/checkout"
  to = "/.netlify/functions/checkout"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/.netlify/functions/signup"
  status = 200
