[build]
  functions = "lambda"
  command = "hugo && env NSPC=$(echo $BRANCH | tr a-z A-Z) npm run build:lambda"
  
[[redirects]]
  from = "/checkout"
  to = "/.netlify/functions/checkout"
  status = 200
