[build]
  functions = "lambda"
  command = "hugo && npm run build:lambda"
  
[context.phase3]
  environment = { VAR_ENV = "STAGING" }

[[redirects]]
  from = "/checkout"
  to = "/.netlify/functions/checkout"
  status = 200
