[build]
  functions = "lambda"
  command = "hugo && npm run build:lambda"
  
# [context.branch-deploy]
#   environment = { NSPC = "STAGING" }

[context.phase3]
  environment = { NSPC = "STAGING" }

[[redirects]]
  from = "/checkout"
  to = "/.netlify/functions/checkout"
  status = 200
